# Generated by Django 5.1.4 on 2024-12-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
